const GET_ALL_POSTS = "GET_ALL_POTS";
const ADD_POST = "ADD_POST";
const DELETE_POST = "DELETE_POST";
const EDIT_POST = "EDIT_POST";
const FILTER_POSTS = "FILTER_POSTS";
const VIEW_POSTS = "VIEW_POSTS";

export default {
  GET_ALL_POSTS,
  ADD_POST,
  DELETE_POST,
  EDIT_POST,
  FILTER_POSTS,
  VIEW_POSTS
};
